USER_APP_OBJS =	output/userApp/main.o \
		output/userApp/shell.o \
		output/userApp/memTestCase.o \
		output/userApp/RR_ScheduleTest.o \
		output/userApp/Prio_ScheduleTest.o \
		output/userApp/userTasks.o
